# -*- coding: utf-8 -*-
"""Taspalm · dictionnaire français → anglais du site miroir /en/.
Chaque clé est un fragment de texte tel qu'il apparaît dans les pages françaises générées (espaces extérieurs retirés).
Un fragment absent est signalé par build.py dans _a-traduire.txt. Yann Tassoua · 2026-09-18"""

TITRES_EN = {
 "index.html":"Taspalm · Palm oil, cocoa and safou from the Likouala, Congo",
 "l-exploitation.html":"The Taspalm farm, at Ibenga since 2006",
 "produits.html":"Our products · palm oil, cocoa, safou, honey, pineapple, maize, vegetables",
 "huile-de-palme.html":"Red palm oil from the Likouala, pressed on the farm",
 "cacao.html":"Ibenga cocoa, fermented under leaves and sun-dried",
 "safou.html":"Safou, the purple fruit of the Likouala",
 "terroir.html":"The land · Ibenga, Enyellé, Likouala, between the Ibenga and the Ubangi",
 "professionnels.html":"Professionals · buy, process and distribute with Taspalm",
 "visiter.html":"Visit the farm at Ibenga, Likouala",
 "contact.html":"Contact · write to Taspalm, Congo and Europe",
 "mentions-legales.html":"Legal notice",
 "confidentialite.html":"Privacy",
}
DESC_EN = {
 "index.html":"Taspalm, a farm at Ibenga (Likouala, Republic of the Congo) since 2006: palm oil, cocoa, safou, honey, pineapple, maize and vegetables, grown, processed on site and sold direct.",
 "l-exploitation.html":"Who we are: a farm founded in 2006 at Ibenga, Enyellé district, in the Likouala. What we do, what we do not do, the people and the dates.",
 "produits.html":"Seven crops on a single piece of land: palm oil, cocoa, safou, honey, pineapple, maize and vegetables. Origin, season, form and packaging of every Taspalm product.",
 "huile-de-palme.html":"Unrefined red palm oil, extracted from the bunches of the Taspalm farm at Ibenga within days of harvest. Drums, barrels and retail, sample on request.",
 "cacao.html":"Single-origin cocoa beans from Ibenga, Likouala: pods opened on harvest day, fermented in boxes under banana leaves, dried on racks. For chocolate makers and processors.",
 "safou.html":"Safou from the Likouala, picked ripe from the tree: fresh in season, processed the rest of the year. A Central African fruit offered by the Taspalm farm.",
 "terroir.html":"The Taspalm estate lies at Ibenga, Enyellé district, Likouala department, where the Ibenga meets the Ubangi. Soil, forest, water and growing method.",
 "professionnels.html":"Distributors, processors, food service, investors: four ways to work with the Taspalm farm, direct, starting from your need.",
 "visiter.html":"Come to Ibenga: a day on the farm, from the palm to the press. Visits, immersions and training, access from Impfondo.",
 "contact.html":"Write to or call Taspalm: contact details in Congo and Europe, address of the estate at Ibenga, Likouala.",
 "mentions-legales.html":"Legal notice of the Taspalm website.",
 "confidentialite.html":"Privacy policy of the Taspalm website: no trackers, fonts hosted on the site, forms to come.",
}

TX = {
# --- identité, lieux, mots isolés
"TASPALM":"TASPALM","T":"T","Taspalm":"Taspalm","contact@taspalm.com":"contact@taspalm.com","© Taspalm 2026":"© Taspalm 2026",
"I":"I","II":"II","III":"III","IV":"IV","FR":"FR","Menu":"Menu","Fermer":"Close","WhatsApp":"WhatsApp",
"Ibenga":"Ibenga","Ibenga,":"Ibenga,","Oubangui":"Ubangi","Congo":"Congo","Europe":"Europe","Enyellé,":"Enyellé,","Likouala.":"Likouala.",
"Ibenga · Likouala":"Ibenga · Likouala","Ibenga, district d'Enyellé":"Ibenga, Enyellé district","Likouala, République du Congo":"Likouala, Republic of the Congo",
"Confluence Ibenga · Oubangui":"Confluence of the Ibenga and the Ubangi","DOMAINE · IBENGA":"ESTATE · IBENGA","RDC →":"DRC →","← IMPFONDO":"← IMPFONDO",
"Navigation principale":"Main navigation","Version française":"Version française","English version":"English version",
"Accueil":"Home","Nos produits":"Our products","Le terroir":"The land","Professionnels":"Professionals","Visiter":"Visit","Contact":"Contact",
"L'exploitation":"The farm","Mentions légales":"Legal notice","Confidentialité":"Privacy","Qui nous sommes":"Who we are","Venir à Ibenga":"Come to Ibenga",
"L'Exploitation · Taspalm":"The Farm · Taspalm","L'exploitation · Taspalm":"The farm · Taspalm","Nos produits · Taspalm":"Our products · Taspalm",
"Huile de palme · Taspalm":"Palm oil · Taspalm","Cacao · Taspalm":"Cocoa · Taspalm","Safou · Taspalm":"Safou · Taspalm","Le terroir · Taspalm":"The land · Taspalm",
"Professionnels · Taspalm":"Professionals · Taspalm","Visiter · Taspalm":"Visit · Taspalm","Contact · Taspalm":"Contact · Taspalm",
"Mentions légales · Taspalm":"Legal notice · Taspalm","Confidentialité · Taspalm":"Privacy · Taspalm",
# --- produits
"Huile de palme":"Palm oil","Cacao":"Cocoa","Safou":"Safou","Miel":"Honey","Ananas":"Pineapple","Maïs":"Maize","Légumes":"Vegetables","Plusieurs produits":"Several products",
"Huile":"Oil","Fèves":"Beans","Fruit":"Fruit","Ruchers":"Apiaries","Vivrier":"Food crop","Céréale de base":"Staple grain","Récolté mûr":"Picked ripe","Frais, de saison":"Fresh, in season",
"Miel, ananas, maïs, légumes":"Honey, pineapple, maize, vegetables","Palmier, cacao, safou, miel, ananas, maïs, légumes":"Oil palm, cocoa, safou, honey, pineapple, maize, vegetables",
"Huile, cacao, miel":"Oil, cocoa, honey","Huile brute":"Crude oil","Huile brute non raffinée":"Unrefined crude oil","Huile végétale":"Vegetable oil",
"Huile de palme rouge Taspalm":"Taspalm red palm oil","Huile de palme brute non raffinée, pressée sur place à Ibenga, Likouala.":"Unrefined crude palm oil, pressed on site at Ibenga, Likouala.",
"Cacao Taspalm, fèves séchées":"Taspalm cocoa, dried beans","Fèves de cacao fermentées sous feuilles de bananier et séchées sur claies, origine Ibenga, Likouala.":"Cocoa beans fermented under banana leaves and dried on racks, origin Ibenga, Likouala.",
"Safou Taspalm":"Taspalm safou","Safou frais en saison et transformé hors saison, cueilli mûr à Ibenga, Likouala.":"Safou, fresh in season and processed out of season, picked ripe at Ibenga, Likouala.",
"Fèves séchées":"Dried beans","Frais · transformé":"Fresh · processed","Miel · rayon":"Honey · comb","Épi · grain":"Cob · grain","Frais":"Fresh","Transformé":"Processed",
"Pressage sur place":"Pressed on site","Récolte":"Harvest","Forme":"Form","Conditionnement":"Packaging","Conditionnements":"Packaging","Origine":"Origin",
"Transformation":"Processing","Procédé":"Process","Conservation":"Shelf life","Capacité mensuelle":"Monthly capacity","Variété":"Variety","Fermentation":"Fermentation",
"Durée de fermentation":"Fermentation time","Séchage":"Drying","Humidité finale":"Final moisture","Saison":"Season","Conservation du frais":"Shelf life when fresh",
"Volume par saison":"Volume per season","Expédition du frais":"Shipping when fresh","En caisses, sous feuilles de bananier":"In boxes, under banana leaves","Sur claies, au soleil":"On racks, in the sun",
"Bidon":"Drum","Fût":"Barrel","Détail":"Retail","Échantillon":"Sample","Sac":"Bag","Lot minimum":"Minimum lot","Fiche d'analyse":"Analysis sheet","Disponibilité":"Availability",
"Sur demande, gratuit · à confirmer":"On request, free · to be confirmed","Frais en saison · transformé hors saison":"Fresh in season · processed out of season",
"À produire par l'exploitation":"To be produced by the farm","Fiche détaillée à venir":"Detailed sheet to come","La fiche complète":"Full product sheet","La fiche.":"The sheet.",
"Toute la collection":"The whole collection","Voir la collection":"See the collection","Les autres produits":"The other products","de l'exploitation.":"of the farm.",
"Trois produits":"Three products","emblématiques,":"that stand out,","quatre cultures de saison.":"four seasonal crops.","Sept cultures,":"Seven crops,","une seule terre.":"one piece of land.",
"Balayez pour voir les produits":"Swipe to see the products",
"Chaque produit porte son origine, sa saison de récolte et son mode de transformation. Rien n'est acheté ailleurs pour être revendu.":"Every product carries its origin, its harvest season and how it is processed. Nothing is bought elsewhere to be resold.",
"Trois produits emblématiques et quatre cultures de saison. Chaque fiche dit ce que nous savons, et laisse visible ce qui reste à préciser.":"Three signature products and four seasonal crops. Each sheet says what we know, and leaves visible what remains to be confirmed.",
"Chaque ligne porte son statut. Les crochets ne sont pas des oublis, ce sont les questions à poser à l'exploitation.":"Every line carries its status. The brackets are not omissions, they are the questions to put to the farm.",
"Extraite dans les jours qui suivent la récolte. Conditionnements pro et détail.":"Extracted within days of harvest. Trade and retail packaging.",
"Fèves fermentées et séchées sur claies. Pour transformateurs et chocolatiers.":"Beans fermented and dried on racks. For processors and chocolate makers.",
"Le fruit de la Likouala, cueilli mûr. Frais en saison, transformé le reste de l'année.":"The fruit of the Likouala, picked ripe. Fresh in season, processed the rest of the year.",
"Rouge, dense, parfumée. Extraite des régimes dans les jours qui suivent la récolte, avant que le fruit ne fermente. Pour la cuisine, la transformation et le détail.":"Red, dense, fragrant. Extracted from the bunches within days of harvest, before the fruit ferments. For cooking, processing and retail.",
"Cabosses ouvertes le jour de la récolte, fèves fermentées en caisses sous feuilles de bananier, puis séchées sur claies. Pour chocolatiers et transformateurs.":"Pods opened on harvest day, beans fermented in boxes under banana leaves, then dried on racks. For chocolate makers and processors.",
"Le fruit violet de la Likouala, cueilli mûr sur l'arbre. Frais pendant la saison, transformé le reste de l'année. Un produit que peu d'exploitations proposent hors du Congo.":"The purple fruit of the Likouala, picked ripe from the tree. Fresh during the season, processed the rest of the year. A product few farms offer outside Congo.",
"Récolté dans les ruchers installés en lisière de forêt. Les abeilles pollinisent au passage le maïs, les légumes et les safoutiers.":"Harvested from apiaries set at the forest edge. On the way, the bees pollinate the maize, the vegetables and the safou trees.",
"Cueilli à maturité, pas avant. Vendu frais dans le département, et sur demande au-delà.":"Picked ripe, not before. Sold fresh within the department, and on request beyond.",
"Cultivé pour le village et le marché local. En épi ou en grain, selon la demande.":"Grown for the village and the local market. On the cob or as grain, as required.",
"Aubergines africaines, gombos, piments, feuilles. La liste exacte suit la saison et reste à établir avec l'exploitation.":"African eggplants, okra, chillies, leaves. The exact list follows the season and remains to be set with the farm.",
"Toute l'année · à confirmer":"All year · to be confirmed",
"Extraite des régimes de noix de palme du domaine, dans les jours qui suivent la récolte. Dense, parfumée, pour la cuisine et la transformation.":"Extracted from the estate's palm fruit bunches within days of harvest. Dense, fragrant, for cooking and processing.",
"rouge, pressée sur place.":"red, pressed on site.","fermenté sous feuilles, séché au soleil.":"fermented under leaves, sun-dried.","le fruit violet de la Likouala.":"the purple fruit of the Likouala.",
"Cabosses ouvertes le jour de la récolte, fèves fermentées en caisses de bois puis séchées sur claies. Pour chocolatiers et transformateurs qui veulent une origine unique.":"Pods opened on harvest day, beans fermented in wooden boxes then dried on racks. For chocolate makers and processors who want a single origin.",
"Cueilli mûr sur l'arbre, vendu frais pendant la saison et transformé le reste de l'année. Un fruit que peu d'exploitations proposent hors du Congo.":"Picked ripe from the tree, sold fresh during the season and processed the rest of the year. A fruit few farms offer outside Congo.",
"De l'arbre":"From the tree","à vous.":"to you.","au bidon,":"to the drum,","tout se fait ici.":"everything happens here.",
"Trois moments. Les photographies réelles de chaque étape sont à faire sur place.":"Three moments. The real photographs of each step are to be taken on site.",
"Trois étapes, un seul lieu. Ce que l'exploitation affirme sur sa transformation reste à documenter avec elle, photo par photo.":"Three steps, one place. What the farm says about its processing remains to be documented with it, photo by photo.",
"Le régime":"The bunch","Le pressage":"The pressing","Le départ":"The departure","La cabosse":"The pod","La fermentation":"The fermentation","Le séchage":"The drying",
"L'arbre":"The tree","La cueillette":"The picking","Le voyage":"The journey","La récolte":"The harvest","La transformation":"The processing",
"Les régimes sont coupés à maturité, quand les noix rougissent. Ils ne restent pas au sol.":"The bunches are cut when ripe, as the fruit turns red. They do not stay on the ground.",
"Cuisson des noix, pressage, décantation. L'atelier est sur le domaine ; son équipement exact est à documenter.":"Cooking of the fruit, pressing, settling. The workshop is on the estate; its exact equipment is to be documented.",
"Mise en bidons ou en fûts, chargement en pirogue ou en camion. Délais et destinations annoncés à la commande.":"Filled into drums or barrels, loaded onto a canoe or a truck. Lead times and destinations stated at order.",
"Cueillie mûre, ouverte le jour même. La pulpe blanche entoure les fèves.":"Picked ripe, opened the same day. The white pulp surrounds the beans.",
"Les fèves passent en caisses de bois, couvertes de feuilles de bananier. C'est là que naît l'arôme.":"The beans go into wooden boxes, covered with banana leaves. This is where the aroma is born.",
"Sur claies, retourné plusieurs fois par jour, jusqu'à l'humidité voulue. Puis ensaché.":"On racks, turned several times a day, down to the target moisture. Then bagged.",
"Le safoutier donne une fois l'an. Les fruits passent du rose au violet foncé quand ils sont prêts.":"The safou tree fruits once a year. The fruit turns from pink to deep purple when ready.",
"Cueilli à la main, à maturité. Le safou ne se conserve pas longtemps frais, tout se joue en quelques jours.":"Picked by hand, when ripe. Safou does not keep long fresh; everything happens within a few days.",
"Frais vers les villes proches, transformé pour aller plus loin. Le procédé de transformation est à documenter.":"Fresh to nearby towns, processed to travel further. The processing method is to be documented.",
"Les régimes de noix de palme, les cabosses et les safous sont cueillis à maturité, sur le domaine.":"Palm fruit bunches, cocoa pods and safou are picked when ripe, on the estate.",
"Pressage de l'huile, fermentation et séchage du cacao, extraction du miel. Sur place, avant que la récolte ne s'abîme.":"Oil pressing, cocoa fermentation and drying, honey extraction. On site, before the harvest spoils.",
"Par la rivière ou par la route, vers Brazzaville, Pointe-Noire et l'export. Volumes et délais annoncés à l'avance.":"By river or by road, to Brazzaville, Pointe-Noire and export. Volumes and lead times stated in advance.",
"Formes et":"Forms and","conditionnements.":"packaging.","Pour qui":"For whom",
"Distributeurs":"Distributors","Transformateurs":"Processors","Restauration":"Food service","Épiceries fines":"Fine grocers","Diaspora":"Diaspora",
"Chocolatiers":"Chocolate makers","Torréfacteurs":"Roasters","Négociants d'origine":"Origin traders","Épiceries africaines":"African grocers",
"Noix de palme et cacao · image d'illustration":"Palm fruit and cocoa · illustrative image","Le domaine · image d'illustration":"The estate · illustrative image",
"Cacaoyer du domaine · image d'illustration":"Cocoa tree on the estate · illustrative image","Lisière de forêt · image d'illustration":"Forest edge · illustrative image",
"Safous sur feuille · image d'illustration":"Safou on a leaf · illustrative image","L'Ibenga · image d'illustration":"The Ibenga · illustrative image",
"Votre besoin en huile de palme":"Your need for palm oil","Votre besoin en cacao":"Your need for cocoa","Votre besoin en safou":"Your need for safou",
"Usage, volume, destination : l'exploitation vous répond depuis Ibenga ou Paris, avec un échantillon si c'est utile.":"Use, volume, destination: the farm replies from Ibenga or Paris, with a sample if useful.",
"Dites-nous":"Tell us","ce qu'il vous faut.":"what you need.",
"Un produit, un usage, un volume, une destination. L'exploitation répond avec une proposition, et un échantillon si c'est utile.":"A product, a use, a volume, a destination. The farm replies with a proposal, and a sample if useful.",
# --- formulaire besoin
"Exprimez votre besoin":"Tell us your need","Envoyer mon besoin":"Send my need","Le produit":"The product","Votre usage":"Your use",
"Volume envisagé, par mois ou par saison":"Expected volume, per month or per season","Pays ou ville de livraison":"Country or city of delivery","Email ou WhatsApp":"Email or WhatsApp",
"Revente":"Resale","Consommation personnelle":"Personal consumption","Partenariat ou investissement":"Partnership or investment","Autre":"Other",
"Produit, usage, volume, pays : quatre réponses suffisent pour que l'exploitation vous fasse une proposition.":"Product, use, volume, country: four answers are enough for the farm to make you a proposal.",
"Le formulaire sera activé prochainement. En attendant, appelez le +242 05 536 16 05 ou écrivez-nous depuis la page Contact.":"The form will be activated soon. Meanwhile, call +242 05 536 16 05 or write to us from the Contact page.",
"Le formulaire sera activé prochainement. En attendant, appelez le +242 05 536 16 05.":"The form will be activated soon. Meanwhile, call +242 05 536 16 05.",
"Appeler l'exploitation":"Call the farm",
# --- accueil
"L'huile, le cacao":"Palm oil, cocoa","et le safou":"and safou","de la Likouala.":"from the Likouala.",
"Sept cultures sur une même terre, à la confluence de l'Ibenga et de l'Oubangui. Récoltées, transformées et expédiées par l'exploitation qui les fait pousser depuis 2006.":"Seven crops on a single piece of land, where the Ibenga meets the Ubangi. Harvested, processed and shipped by the farm that has grown them since 2006.",
"coordonnées à fournir":"coordinates to be provided","Coordonnées à fournir":"Coordinates to be provided",
"Nous ne sommes pas un négociant. Nous sommes":"We are not traders. We are","ceux qui plantent,":"the ones who plant,","ceux qui récoltent, et ceux qui pressent.":"the ones who harvest, and the ones who press.",
"Ce que vous recevez a poussé ici, entre deux rivières, et n'a quitté Ibenga qu'une fois":"What you receive grew here, between two rivers, and only left Ibenga once","prêt à voyager.":"ready to travel.",
"Une terre entre":"A land between","deux rivières.":"two rivers.",
"Le domaine est installé au village d'Ibenga, dans le district d'Enyellé, là où l'Ibenga rejoint l'Oubangui. Une terre alluviale, une forêt qui protège les cultures.":"The estate sits in the village of Ibenga, in the Enyellé district, where the Ibenga meets the Ubangi. Alluvial soil, and a forest that shelters the crops.",
"Depuis 2006, l'exploitation cultive, transforme sur place, et fait vivre les familles du village qui y travaillent.":"Since 2006 the farm has grown, processed on site, and supported the village families who work there.",
"Année de fondation":"Year founded","Surface cultivée, à confirmer":"Cultivated area, to be confirmed","Cultures":"Crops","Emplois au village, à fournir":"Jobs in the village, to be provided",
"Découvrir le terroir":"Discover the land","Acheter, transformer,":"Buy, process,","distribuer.":"distribute.","Acheter, transformer, distribuer":"Buy, process, distribute",
"L'exploitation fournit en direct, sans intermédiaire, avec des volumes et des délais annoncés à l'avance. Chaque relation commence par un besoin clairement exprimé.":"The farm supplies direct, with no middleman, with volumes and lead times stated in advance. Every relationship starts with a clearly expressed need.",
"Distributeurs et revendeurs":"Distributors and resellers","Détail et gros":"Retail and wholesale","Transformateurs agroalimentaires":"Food processors","Matière première":"Raw material",
"Restauration et hôtellerie":"Restaurants and hotels","Approvisionnement":"Supply","Partenaires et investisseurs":"Partners and investors","Sur dossier":"On file",
"Tout sur les partenariats":"All about partnerships","Venir à Ibenga,":"Come to Ibenga,","voir de ses yeux.":"see it with your own eyes.",
"L'exploitation reçoit des visiteurs, des étudiants et des porteurs de projet. On marche dans la plantation, on assiste au pressage, on goûte. L'accès et les séjours sont décrits page Visiter.":"The farm welcomes visitors, students and project leaders. You walk the plantation, watch the pressing, taste. Access and stays are described on the Visit page.",
"Préparer une visite":"Plan a visit","Rive de l'Ibenga · image d'illustration":"Bank of the Ibenga · illustrative image","Vue aérienne d'illustration · à remplacer":"Illustrative aerial view · to be replaced",
# --- l'exploitation
"Une exploitation agricole":"A farm","à Ibenga,":"at Ibenga,","depuis 2006.":"since 2006.",
"Ce que nous sommes, ce que nous faisons, et ce que nous refusons de faire. Sans photographie de banque, sans chiffre inventé.":"What we are, what we do, and what we refuse to do. No stock photography, no invented figure.",
"Une exploitation, c'est un lieu et des gens. Le lieu s'appelle Ibenga. Les gens sont ceux qui y vivent.":"A farm is a place and people. The place is called Ibenga. The people are those who live there.",
"Nous plantons, nous récoltons, nous pressons, nous séchons. Puis nous chargeons la pirogue.":"We plant, we harvest, we press, we dry. Then we load the canoe.","Tout ce qui porte notre nom est passé par nos mains.":"Everything that bears our name has passed through our hands.",
"Nous ne promettons pas des tonnes que nous n'avons pas. Nous disons ce que la saison donne, et quand.":"We do not promise tonnes we do not have. We say what the season gives, and when.",
"Ce que nous faisons,":"What we do,","et pas.":"and do not.","Deux colonnes courtes valent mieux qu'une page de valeurs.":"Two short columns are worth more than a page of values.",
"Cultiver sept espèces":"Grow seven species","Transformer sur place":"Process on site","Vendre en direct":"Sell direct","Sans intermédiaire":"No middleman","Recevoir":"Welcome visitors","Visites et formations":"Visits and training",
"Acheter pour revendre":"Buy to resell","Rien d'ailleurs":"Nothing from elsewhere","Promettre un volume sans récolte":"Promise a volume without a harvest","La saison décide":"The season decides",
"Mélanger les origines":"Mix origins","Une terre, un nom":"One land, one name","Cacher ce qu'on ne sait pas":"Hide what we do not know","Les crochets restent visibles":"The brackets stay visible",
"Vingt ans,":"Twenty years,","en cinq dates.":"in five dates.",
"Seule la fondation est établie. Les autres jalons sont à fournir par l'exploitation, ils remplacent les emplacements ci-dessous.":"Only the founding is established. The other milestones are to be provided by the farm; they replace the placeholders below.",
"Fondation de l'exploitation à Ibenga, district d'Enyellé.":"Founding of the farm at Ibenga, Enyellé district.","vérifié · site actuel":"verified · current website",
"Premières plantations de cacao. Date et surface à fournir.":"First cocoa plantings. Date and area to be provided.","Mise en service de l'atelier de pressage. À confirmer.":"Pressing workshop brought into service. To be confirmed.",
"Premiers ruchers, première récolte de miel. À confirmer.":"First apiaries, first honey harvest. To be confirmed.","Première expédition hors du département. Destination à fournir.":"First shipment outside the department. Destination to be provided.",
"Les gens":"The people","Aucun portrait n'est fabriqué. Les photographies, les prénoms et les fonctions sont à fournir, avec l'accord de chacun.":"No portrait is fabricated. Photographs, first names and roles are to be provided, with each person's consent.",
"portrait réel":"real portrait","à fournir":"to be provided","Fondateur · Ibenga":"Founder · Ibenga","Direction de l'exploitation":"Farm management","Représentation · Europe":"Representation · Europe",
"Ce que nous savons,":"What we know,","ce qu'il reste à mesurer.":"what remains to be measured.",
"Un site qui affiche des chiffres doit pouvoir les sourcer. Ceux-ci sont donnés avec leur statut.":"A website that shows figures must be able to source them. These are given with their status.",
"Fondation · vérifié":"Founded · verified","Cultures · vérifié":"Crops · verified","Surface totale · non vérifié":"Total area · not verified","Personnes employées · à fournir":"People employed · to be provided",
"Forêt de la Likouala · image d'illustration":"Likouala forest · illustrative image",
# --- terroir
"Ibenga, district d'Enyellé, département de la Likouala, au nord de la République du Congo. Là où l'Ibenga rejoint l'Oubangui.":"Ibenga, Enyellé district, Likouala department, in the north of the Republic of the Congo. Where the Ibenga meets the Ubangi.",
"Le domaine est bordé par la rivière Ibenga à son point de confluence avec l'Oubangui, qui marque la frontière avec la République démocratique du Congo. C'est ce que dit le site actuel de l'exploitation, et c'est cohérent avec la géographie du département.":"The estate is bordered by the Ibenga river at its confluence with the Ubangi, which marks the border with the Democratic Republic of the Congo. This is what the farm's current website says, and it is consistent with the geography of the department.",
"relayé · à confirmer sur place":"relayed · to be confirmed on site",
"L'accès se fait par voie fluviale ou par la route depuis Impfondo, chef-lieu du département. Les durées de trajet, la saison praticable et les coordonnées exactes sont à fournir par l'exploitation.":"Access is by river or by road from Impfondo, the department's main town. Travel times, the passable season and exact coordinates are to be provided by the farm.",
"Installation":"Established","Surface totale à confirmer":"Total area to be confirmed","Depuis Impfondo, à fournir":"From Impfondo, to be provided",
"Schéma de situation":"Location diagram","Schéma de situation, sans échelle":"Location diagram, not to scale","position schématique, à confirmer":"schematic position, to be confirmed",
"Ce que la terre":"What the land","donne.":"gives.","Climat, sol et pluviométrie sont à documenter avec des sources. Rien n'est affiché ici qui ne soit sourcé.":"Climate, soil and rainfall are to be documented with sources. Nothing is shown here that is not sourced.",
"Le sol":"The soil","Alluvial, entre deux rivières":"Alluvial, between two rivers","Une terre déposée par les crues, profonde. Analyse de sol :":"Deep soil laid down by the floods. Soil analysis:",
"La forêt":"The forest","Une lisière qui protège":"An edge that protects","Ombre pour les cacaoyers, abeilles pour les ruchers, brise-vent pour le reste. Surface boisée conservée :":"Shade for the cocoa trees, bees for the apiaries, a windbreak for the rest. Woodland retained:",
"L'eau":"The water","La rivière, chemin et frontière":"The river, road and border","Elle irrigue, elle transporte, elle limite. Pluviométrie annuelle :":"It irrigates, it carries, it bounds. Annual rainfall:",
"Une méthode,":"A method,","à écrire avec l'exploitation.":"to be written with the farm.",
"L'exploitation indique cultiver sans intrants de synthèse. Nous l'écrivons ici tel qu'elle le dit, et nous le documenterons : fertilisation, protection des cultures, gestion de l'ombre, rotation des vivriers.":"The farm states that it grows without synthetic inputs. We write it here as the farm says it, and we will document it: fertilisation, crop protection, shade management, rotation of food crops.",
"non vérifié":"not verified","Fertilisation":"Fertilisation","Protection des cultures":"Crop protection","Ombre et agroforesterie":"Shade and agroforestry","Certifications":"Certifications","Aucune déclarée":"None declared",
"Régime de noix de palme · image d'illustration":"Palm fruit bunch · illustrative image",
"Une exploitation qui tourne, c'est des emplois qui ne demandent pas de partir à Brazzaville,":"A working farm means jobs that do not require leaving for Brazzaville,","et des savoir-faire qui restent à Ibenga.":"and skills that stay in Ibenga.",
"Personnes employées et familles concernées : à fournir. Nous n'affichons pas de chiffre que nous ne pouvons pas sourcer.":"People employed and families involved: to be provided. We do not show a figure we cannot source.","Venir voir":"Come and see",
# --- professionnels
"L'exploitation fournit en direct, sans intermédiaire, avec des volumes et des délais annoncés à l'avance. Quatre façons de travailler ensemble, un seul point de départ : votre besoin.":"The farm supplies direct, with no middleman, with volumes and lead times stated in advance. Four ways to work together, one starting point: your need.",
"Le dossier de l'exploitation":"The farm dossier","Quatre façons de travailler":"Four ways to work","avec l'exploitation.":"with the farm.",
"Chaque voie a son interlocuteur. Aucune ne passe par un formulaire générique.":"Each route has its own contact person. None goes through a generic form.",
"Industriels agroalimentaires":"Food manufacturers","Huile, cacao, safou, miel, en gros ou au détail, avec des volumes engagés sur la saison.":"Oil, cocoa, safou, honey, wholesale or retail, with volumes committed for the season.",
"Matière première brute ou semi-transformée, à cahier des charges.":"Raw or semi-processed material, to specification.",
"Approvisionnement régulier en huile, fruits et légumes, à Brazzaville et Pointe-Noire d'abord.":"Regular supply of oil, fruit and vegetables, in Brazzaville and Pointe-Noire first.",
"Extension des surfaces, équipement de transformation, logistique fluviale. Sur dossier.":"Expansion of the planted area, processing equipment, river logistics. On file.","Recevoir le dossier":"Receive the dossier",
"Comment ça se passe,":"How it works,","en quatre temps.":"in four steps.","Les délais indiqués sont ceux que l'exploitation devra tenir. Ils sont à confirmer avant publication.":"The lead times shown are the ones the farm will have to keep. They are to be confirmed before publication.",
"Le besoin.":"The need.","Vous nous dites le produit, l'usage, le volume et la destination. Nous répondons, avec un échantillon si c'est utile. Délai :":"You tell us the product, the use, the volume and the destination. We reply, with a sample if useful. Lead time:",
"Le devis.":"The quote.","Volume, conditionnement, incoterm, délai. Une page, pas dix.":"Volume, packaging, incoterm, lead time. One page, not ten.",
"La commande.":"The order.","Acompte :":"Deposit:",". La récolte ou le lot est réservé.":". The harvest or the lot is reserved.",
"La livraison.":"The delivery.","Par rivière puis route, ou enlèvement à Brazzaville / Pointe-Noire. Export :":"By river then road, or collection in Brazzaville / Pointe-Noire. Export:",
"Tout en un PDF,":"All in one PDF,","mis à jour chaque saison.":"updated every season.",
"Chiffres, cultures, capacités, gouvernance, contacts. C'est la pièce qui manque le plus au site actuel, et celle qu'un acheteur ou un investisseur demande en premier. À produire avec l'exploitation.":"Figures, crops, capacities, governance, contacts. It is the piece most missing from the current website, and the one a buyer or an investor asks for first. To be produced with the farm.",
"Télécharger le dossier":"Download the dossier","document à produire":"document to be produced","Aire de séchage · image d'illustration":"Drying yard · illustrative image",
"Ce qu'on nous":"What people","demande.":"ask us.","Les réponses sont à écrire par l'exploitation. Les questions, elles, sont celles que posent les acheteurs.":"The answers are for the farm to write. The questions are the ones buyers ask.",
"Quel est le volume minimum de commande ?":"What is the minimum order volume?","Réponse à fournir par l'exploitation, par produit.":"Answer to be provided by the farm, per product.",
"Livrez-vous hors du Congo ?":"Do you deliver outside Congo?","Le site actuel parle d'export. Destinations desservies, incoterms et documents à préciser.":"The current website mentions export. Destinations served, incoterms and documents to be specified.",
"Quels délais entre la commande et la livraison ?":"How long between order and delivery?","Selon le produit, la saison et la destination. Fourchettes à établir.":"Depending on the product, the season and the destination. Ranges to be set.",
"Avez-vous des certifications ?":"Do you hold any certifications?","Aucune n'est déclarée sur le site actuel. Si une démarche est en cours, elle sera indiquée ici avec sa date.":"None is declared on the current website. If a process is under way, it will be shown here with its date.",
"Comment se passe le paiement ?":"How does payment work?","Acompte, solde, moyens de paiement acceptés : à définir.":"Deposit, balance, accepted payment methods: to be defined.",
# --- visiter
"L'exploitation reçoit des visiteurs, des étudiants et des porteurs de projet. On marche dans la plantation, on assiste au pressage, on goûte.":"The farm welcomes visitors, students and project leaders. You walk the plantation, watch the pressing, taste.",
"Une journée":"A day","sur l'exploitation.":"on the farm.","Le déroulé ci-dessous est une proposition. Il doit être validé, et vécu une fois, avant d'être promis.":"The schedule below is a proposal. It must be validated, and lived through once, before being promised.",
"Le matin":"Morning","La plantation":"The plantation","Palmiers, cacaoyers, safoutiers, ruchers en lisière. On marche, on cueille, on explique ce qui pousse et quand.":"Oil palms, cocoa trees, safou trees, apiaries at the forest edge. You walk, you pick, we explain what grows and when.",
"Midi":"Midday","L'atelier":"The workshop","Le pressage de l'huile, la fermentation du cacao, selon la saison. On regarde, on sent, on comprend pourquoi ça se fait ici.":"Oil pressing, cocoa fermentation, depending on the season. You watch, you smell, you understand why it is done here.",
"Le soir":"Evening","La rivière":"The river","Le chargement des pirogues, le village. On goûte ce qu'on a vu pousser.":"The loading of the canoes, the village. You taste what you saw growing.",
"Y aller,":"Getting there,","y rester.":"staying.","Depuis Brazzaville":"From Brazzaville","Depuis Impfondo":"From Impfondo","Hébergement":"Accommodation","Saison recommandée":"Recommended season","Formalités":"Formalities",
"Aucune de ces lignes n'est renseignée par le site actuel. Elles sont à remplir par l'exploitation avant mise en ligne.":"None of these lines is given on the current website. They are to be filled in by the farm before going live.",
"Sur la rive · image d'illustration":"On the bank · illustrative image","Visite, immersion,":"Visit, immersion,","formation.":"training.",
"Trois durées proposées, à confirmer par l'exploitation : ce qu'elle peut réellement accueillir, à quel prix, et combien de personnes à la fois.":"Three lengths proposed, to be confirmed by the farm: what it can really host, at what price, and how many people at a time.",
"La visite":"The visit","Une journée · [ tarif ]":"One day · [ price ]","L'immersion":"The immersion","Trois jours · [ tarif ]":"Three days · [ price ]","La formation":"The training","[ durée ] · cacao ou apiculture · [ tarif ]":"[ length ] · cocoa or beekeeping · [ price ]",
"Dites-nous qui vous êtes et ce que vous venez voir. L'exploitation vous répond avec les dates possibles.":"Tell us who you are and what you are coming to see. The farm replies with the possible dates.",
"Votre nom":"Your name","Vous venez en tant que":"You are coming as","Visiteur":"Visitor","Étudiant":"Student","Porteur de projet":"Project leader","Acheteur":"Buyer","Presse":"Press","Période envisagée":"Intended period","Envoyer":"Send",
# --- contact
"Écrire":"Write","à l'exploitation.":"to the farm.","Une seule adresse, deux pays, des gens qui répondent. Les numéros ci-dessous sont ceux du site actuel.":"One address, two countries, people who answer. The numbers below are those of the current website.",
"et Paris.":"and Paris.","adresse unique à créer":"single address to be created","Le domaine":"The estate","Nous écrire":"Write to us","Pour tout ce qui n'est ni un besoin produit ni une visite.":"For anything that is neither a product need nor a visit.",
"Votre message":"Your message","Écrire à l'exploitation":"Write to the farm","Téléphones":"Telephones","Congo +242 05 536 16 05 · +242 06 993 23 64":"Congo +242 05 536 16 05 · +242 06 993 23 64","Europe +33 7 80 73 53 82 · +33 6 49 10 66 50":"Europe +33 7 80 73 53 82 · +33 6 49 10 66 50",
"Les trois adresses e-mail et les cinq numéros du site actuel sont remplacés par une adresse professionnelle unique et quatre numéros nommés. Qui répond à quel numéro : à fournir.":"The three e-mail addresses and five numbers of the current website are replaced by a single professional address and four named numbers. Who answers which number: to be provided.",
"Exploitation agricole, Ibenga, district d'Enyellé, département de la Likouala, République du Congo. Fondée en 2006.":"Farm, Ibenga, Enyellé district, Likouala department, Republic of the Congo. Founded in 2006.",
"Exploitation agricole à Ibenga, district d'Enyellé, département de la Likouala, République du Congo.":"Farm at Ibenga, Enyellé district, Likouala department, Republic of the Congo.",
"Les photographies du domaine ont été prises sur place en 2021 et 2022. Celles qui portent la mention « image d'illustration » sont des visuels provisoires. Les valeurs entre crochets sont en cours de validation.":"The photographs of the estate were taken on site in 2021 and 2022. Those marked \"illustrative image\" are temporary visuals. The values in brackets are being validated.",
"Cabosse de cacao ouverte, fèves fraîches dans leur pulpe blanche, et cabosses entières sur des feuilles, photographie d'avril 2025":"Open cocoa pod with fresh beans in their white pulp, and whole pods on leaves, photograph from April 2025",
"Cabosses de cacao récoltées, posées sur une table de bois, photographie d'avril 2025":"Harvested cocoa pods on a wooden table, photograph from April 2025",
"Cabosses de cacao vertes sur le tronc d'un cacaoyer du domaine, photographie d'avril 2025":"Green cocoa pods on the trunk of a cocoa tree on the estate, photograph from April 2025",
"Fèves de cacao étalées pour le séchage, photographie d'avril 2025":"Cocoa beans spread out for drying, photograph from April 2025",
"Cacaoyers en production sous les palmiers à huile, photographie d'avril 2025":"Cocoa trees in production under the oil palms, photograph from April 2025",
"Caisses de fermentation du cacao en bois, photographie d'avril 2025":"Wooden cocoa fermentation boxes, photograph from April 2025",
"Claies de séchage du cacao sous les palmiers, photographie d'avril 2025":"Cocoa drying racks under the palms, photograph from April 2025",
"Régimes de noix de palme fraîchement coupés, photographie d'avril 2025":"Freshly cut palm fruit bunches, photograph from April 2025",
"Noix de palme rouges et orange détachées du régime, photographie d'avril 2025":"Red and orange palm fruit loosened from the bunch, photograph from April 2025",
"Ruche en bois avec ses abeilles à l'entrée, en lisière de la plantation, photographie d'avril 2025":"Wooden hive with bees at the entrance, at the edge of the plantation, photograph from April 2025",
"Ruche installée sous un arbre du domaine, photographie d'avril 2025":"Hive set under a tree on the estate, photograph from April 2025",
"Ananas sur pied dans le champ, photographie d'avril 2025":"Pineapple on the plant in the field, photograph from April 2025",
"Champ d'ananas du domaine au lever du jour, photographie d'avril 2025":"The estate's pineapple field at sunrise, photograph from April 2025",
"Corossols entiers et corossol coupé sur des feuilles, photographie d'avril 2025":"Whole soursops and a cut soursop on leaves, photograph from April 2025",
"Corossols sur l'arbre, photographie d'avril 2025":"Soursops on the tree, photograph from April 2025",
"Pépinière de jeunes cacaoyers en sachets, photographie d'avril 2025":"Nursery of young cocoa trees in bags, photograph from April 2025",
"Jeunes palmiers à huile en pépinière, photographie d'avril 2025":"Young oil palms in the nursery, photograph from April 2025",
"Arbres fruitiers, jeunes ananas et palmiers le long de la piste du domaine, photographie d'avril 2025":"Fruit trees, young pineapples and palms along the estate track, photograph from April 2025",
"Palmiers à huile adultes du domaine, photographie d'avril 2025":"Mature oil palms on the estate, photograph from April 2025",
"Jeune cacaoyer planté sous les palmiers, photographie d'avril 2025":"Young cocoa tree planted under the palms, photograph from April 2025",
"Régimes de noix de palme · avril 2025":"Palm fruit bunches · April 2025","Claies de séchage du cacao · avril 2025":"Cocoa drying racks · April 2025",
"Noix de palme détachées du régime · avril 2025":"Palm fruit loosened from the bunch · April 2025","Jeunes palmiers en pépinière · avril 2025":"Young palms in the nursery · April 2025",
"Fèves de cacao au séchage · avril 2025":"Cocoa beans drying · April 2025","Cacaoyers sous les palmiers · avril 2025":"Cocoa trees under the palms · April 2025",
"Pépinière de jeunes cacaoyers · avril 2025":"Nursery of young cocoa trees · April 2025","Jeune cacaoyer sous les palmiers · avril 2025":"Young cocoa tree under the palms · April 2025",
"Palmiers à huile adultes · avril 2025":"Mature oil palms · April 2025","La piste du domaine · avril 2025":"The estate track · April 2025",
"Les caisses de fermentation · avril 2025":"The fermentation boxes · April 2025","Une ruche sous un arbre · avril 2025":"A hive under a tree · April 2025",
"Champ d'ananas au lever du jour · avril 2025":"Pineapple field at sunrise · April 2025",
"Les photographies du domaine ont été prises sur place en 2021, 2022 et 2025. Celles qui portent la mention « image d'illustration » sont des visuels provisoires. Les valeurs entre crochets sont en cours de validation.":"The photographs of the estate were taken on site in 2021, 2022 and 2025. Those marked \"illustrative image\" are temporary visuals. The values in brackets are being validated.",
"Confluence de deux rivières vue du ciel, près du domaine, photographie de septembre 2021":"Confluence of two rivers seen from the air, near the estate, photograph from September 2021",
"Barges à quai sur la rivière, vue du ciel, photographie de septembre 2021":"Barges moored on the river, seen from the air, photograph from September 2021",
"Palmiers à huile du domaine Taspalm, photographie d'avril 2022":"Oil palms on the Taspalm estate, photograph from April 2022",
"Piste et palmiers à huile du domaine vus du ciel, photographie d'avril 2022":"Track and oil palms of the estate seen from the air, photograph from April 2022",
"Pépinière de jeunes palmiers sous ombrière, photographie d'avril 2022":"Nursery of young palms under shade netting, photograph from April 2022",
"Jeunes plants en sachets à la pépinière, photographie d'avril 2022":"Young plants in bags at the nursery, photograph from April 2022",
"Rayon de miel du domaine sur une assiette, photographie d'avril 2022":"Honeycomb from the estate on a plate, photograph from April 2022",
"Ananas récoltés sur le domaine, photographie d'août 2022":"Pineapples harvested on the estate, photograph from August 2022",
"Aubergine sur pied dans les cultures vivrières du domaine, photographie d'avril 2022":"Eggplant on the plant in the estate's food crops, photograph from April 2022",
"Jeunes plantations tuteurées sur le domaine, photographie d'avril 2022":"Young staked plantings on the estate, photograph from April 2022",
"Palmiers à huile du domaine · avril 2022":"Oil palms of the estate · April 2022","Image d'illustration":"Illustrative image",
"Barges à quai sur la rivière · septembre 2021":"Barges moored on the river · September 2021","Confluence de deux rivières, vue du ciel · septembre 2021":"Confluence of two rivers, seen from the air · September 2021",
"Pépinière de jeunes palmiers · avril 2022":"Nursery of young palms · April 2022","Le domaine vu du ciel · avril 2022":"The estate seen from the air · April 2022",
"Confluence de deux rivières · septembre 2021":"Confluence of two rivers · September 2021","Jeunes plantations · avril 2022":"Young plantings · April 2022",
"Piste et palmiers · avril 2022":"Track and palms · April 2022","Confluence · septembre 2021":"Confluence · September 2021","Jeunes plants à la pépinière · avril 2022":"Young plants at the nursery · April 2022",
"La plantation vue du ciel · avril 2022":"The plantation seen from the air · April 2022","La rivière · septembre 2021":"The river · September 2021",
"Vue aérienne du domaine Taspalm à Ibenga : palmiers à huile, arbres fruitiers et cultures vivrières, photographie prise en avril 2022":"Aerial view of the Taspalm estate at Ibenga: oil palms, fruit trees and food crops, photograph taken in April 2022",
"Vue aérienne du domaine Taspalm à Ibenga, photographie prise en avril 2022":"Aerial view of the Taspalm estate at Ibenga, photograph taken in April 2022",
# --- mentions, confidentialité
"Mentions":"Legal","légales.":"notice.","Les informations ci-dessous sont à fournir par l'exploitation avant mise en ligne.":"The information below is to be provided by the farm before going live.",
"Éditeur":"Publisher","Siège":"Registered office","Immatriculation":"Registration","Directeur de la publication":"Publishing director","Hébergeur":"Host","Données personnelles":"Personal data","Crédits":"Credits",
"Conception : Yann Tassoua · photographies : [ à créditer ]":"Design: Yann Tassoua · photographs: [ to be credited ]",
"Vos données,":"Your data,","et ce que nous en faisons.":"and what we do with it.","Ce site ne dépose aucun traceur et ne mesure pas son audience. Voici ce qu'il collecte, et ce qu'il ne collecte pas.":"This website sets no trackers and does not measure its audience. Here is what it collects, and what it does not.",
"Traceurs et mesure d'audience":"Trackers and audience measurement","Aucun. Pas de cookie, pas d'outil de statistiques.":"None. No cookie, no analytics tool.","Polices de caractères":"Fonts","Hébergées sur ce site. Aucun appel vers un service tiers.":"Hosted on this site. No call to a third-party service.",
"Formulaires":"Forms","Vos droits":"Your rights","Accès, rectification, suppression : écrire à [ adresse à créer ]":"Access, correction, deletion: write to [ address to be created ]","Responsable du traitement":"Data controller",
"Page gabarit, à compléter avant le branchement des formulaires. Les crochets sont à remplir par l'exploitation.":"Template page, to be completed before the forms are connected. The brackets are to be filled in by the farm.",
# --- images (alt)
"Nature morte de noix de palme, cabosses de cacao ouvertes, safous et pot d'huile sur un lin brun, image d'illustration":"Still life of palm fruit, open cocoa pods, safou and a pot of oil on brown linen, illustrative image",
"Bouteille d'huile de palme rouge à côté de noix de palme et d'une palme, image d'illustration":"Bottle of red palm oil beside palm fruit and a palm frond, illustrative image",
"Cabosses de cacao jaunes et rouges sur le tronc d'un cacaoyer, image d'illustration":"Yellow and red cocoa pods on the trunk of a cocoa tree, illustrative image",
"Safous violets mûrs posés sur une feuille de bananier, image d'illustration":"Ripe purple safou on a banana leaf, illustrative image",
"Pot de miel doré, rayon de miel et cuillère en bois, image d'illustration":"Jar of golden honey, honeycomb and wooden spoon, illustrative image",
"Ananas entier et ananas coupé sur un lin brun, image d'illustration":"Whole and cut pineapple on brown linen, illustrative image",
"Épis de maïs jaune partiellement déshabillés, image d'illustration":"Partly husked ears of yellow maize, illustrative image",
"Aubergines africaines, gombos, piments et feuilles de manioc, image d'illustration":"African eggplants, okra, chillies and cassava leaves, illustrative image",
"Régime de noix de palme rouge accroché au tronc d'un palmier à huile, image d'illustration":"Bunch of red palm fruit on the trunk of an oil palm, illustrative image",
"Atelier de pressage artisanal d'huile de palme avec bassines d'huile rouge, image d'illustration":"Artisanal palm oil pressing workshop with basins of red oil, illustrative image",
"Caisses de fermentation en bois remplies de fèves de cacao sous feuilles de bananier, image d'illustration":"Wooden fermentation boxes full of cocoa beans under banana leaves, illustrative image",
"Village au bord d'une rivière brune en Afrique centrale, cases et pirogues dans la brume du matin, image d'illustration":"Village on the bank of a brown river in Central Africa, huts and canoes in the morning mist, illustrative image",
"Sous-bois de forêt équatoriale traversé de rayons de lumière, image d'illustration":"Equatorial forest undergrowth crossed by rays of light, illustrative image",
"Grappes de safous violets sur les branches d'un safoutier, image d'illustration":"Clusters of purple safou on the branches of a safou tree, illustrative image",
"Pirogue chargée de sacs et de bidons amarrée sur la rive d'une rivière, image d'illustration":"Canoe loaded with sacks and drums moored on a river bank, illustrative image",
"Vue aérienne de rangées de palmiers à huile à la confluence de deux rivières bordées de forêt, image d'illustration":"Aerial view of rows of oil palms at the confluence of two forest-lined rivers, illustrative image",
"Aire de séchage de fèves de cacao sur claies devant un bâtiment agricole, image d'illustration":"Cocoa bean drying yard on racks in front of a farm building, illustrative image",
"Pirogue en bois sur la rive d'une large rivière brune à l'heure bleue, image d'illustration":"Wooden canoe on the bank of a wide brown river at the blue hour, illustrative image",
# --- crochets et statuts
"[ % ] à fournir":"[ % ] to be provided","[ % à définir ]":"[ % to be defined ]","[ OVHcloud, à confirmer ] · sous-traitant technique":"[ OVHcloud, to be confirmed ] · technical subcontractor",
"[ Prénom Nom ]":"[ First name Last name ]","[ RCCM, NIU ]":"[ RCCM, NIU ]","[ adresse ]":"[ address ]","[ année ]":"[ year ]","[ au village ou à Enyellé, à confirmer ]":"[ in the village or at Enyellé, to be confirmed ]",
"[ conditionnement à fournir ]":"[ packaging to be provided ]","[ contenance à fournir ]":"[ capacity to be provided ]","[ format à fournir ]":"[ format to be provided ]","[ forme à fournir ]":"[ form to be provided ]",
"[ h ]":"[ h ]","[ ha ]":"[ ha ]","[ jours ]":"[ days ]","[ jours ] à fournir":"[ days ] to be provided","[ lat · long ]":"[ lat · long ]","[ mm, source à fournir ]":"[ mm, source to be provided ]",
"[ mois ]":"[ month ]","[ mois ] à confirmer":"[ month ] to be confirmed","[ mois à confirmer ]":"[ month to be confirmed ]","[ n ]":"[ n ]","[ nom ]":"[ name ]","[ numéro à confirmer ]":"[ number to be confirmed ]",
"[ poids ] sur demande":"[ weight ] on request","[ poids à fournir ]":"[ weight to be provided ]","[ prestataire ]":"[ provider ]","[ raison sociale, adresse ]":"[ company name, address ]",
"[ raison sociale, forme juridique, capital ]":"[ company name, legal form, capital ]","[ route ou rivière · durée à fournir ]":"[ road or river · duration to be provided ]",
"[ usage des formulaires, durée de conservation ]":"[ use of the forms, retention period ]","[ vol vers Impfondo, à confirmer ]":"[ flight to Impfondo, to be confirmed ]",
"[ à compléter au branchement : destinataire, finalité, durée de conservation ]":"[ to be completed when the forms are connected: recipient, purpose, retention period ]",
"[ à confirmer ]":"[ to be confirmed ]","[ à confirmer ] selon destination":"[ to be confirmed ] depending on destination","[ à documenter ]":"[ to be documented ]","[ à fournir ]":"[ to be provided ]",
"[ à fournir ] bidon, fût, détail":"[ to be provided ] drum, barrel, retail","[ à fournir ] sacs":"[ to be provided ] bags","[ à préciser ]":"[ to be specified ]",
"[ à préciser ] artisanal ou mécanique":"[ to be specified ] artisanal or mechanical","[ à préciser ] séché, pâte, huile":"[ to be specified ] dried, paste, oil",
}
